### ISSUE TITLE
Can't talk on v5.0.0-beta14-rc2

### ISSUE THREAD

**Issue by Gamer92000** [TeamSpeak-Systems/ts-services#10]
After updating to `v5.0.0-beta14-rc2` people can no longer talk normally.
Whispering still works though, so it's not the audio transmission in general.

**Comment by qknight** [comment]
It is safe to go back to the release before which is ts-services beta-58rc12. Thanks for the info, when we tested today we have missed this, sorry.

**Comment by qknight** [comment]
I've depublished the beta-58rc12 until we have fixed this.
