### ISSUE TITLE
Teamspeak homebase does not work

### ISSUE THREAD

**Issue by shystriknsk** [TeamSpeak-Systems/ts-services#11]
I did the installation on a clean server, everything seemed to be installed and started normally. But the appserver log says that it cannot create a matrix database, I attach a screenshot of the log.
![Снимок экрана от 2022-12-15 22-18-17](https://user-images.githubusercontent.com/81510930/207943008-f5e55408-f254-4382-8b6e-a8eb80214f25.png)

**Comment by Gamer92000** [comment]
Works fine for me.
Did you follow the instructions in the README and ran the setup first?

**Comment by shystriknsk** [comment]
yes, I did everything according to the instructions.

**Comment by Gamer92000** [comment]
I would suggest you start over.
* Optionally back up all important data
* shut down all containers
* Remove all volumes (and the `.env` file)
* Run the setup again (and make sure that either the server (traefik) is reachable on port 443 from the outside for letsencrypt or you are using the HTTP compose file)

**Comment by shystriknsk** [comment]
the firewall was turned off

**Comment by qknight** [comment]
The message sometimes appears when starting the services for the first time. The ts-appserver will try to connect to the matrix (synpase) services and if it is not up it will try again later in an loop.

Sometimes synapse is up but does internal stuff so the /_matirx is not working just yet. 

You can try to get more debug with this:

```
appserver:
    image: ...
    restart: on-failure
    stop_grace_period: 1m30s
    environment:
      ...
      - LOG_LEVEL=info
```

Set the LOG_LEVEL of this service to **trace** and do:

```
docker compse up -d
```

And also have a look at the synapse service, if it is up and working using the log:

```
docker logs -f ts-services-synapse-1
```

**Comment by qknight** [comment]
@shystriknsk the firewall was the issue for you so i close this ticket. if you still have this problem, please reopen and leave a comment.

**Comment by Footsiefat** [comment]
@shystriknsk please specify your fix in more detail as i am having the same issue
