### ISSUE TITLE
Planned difference between TeamSpeak 3 and 5

### ISSUE THREAD

**Issue by Sebi94nbg** [TeamSpeak-Systems/ts-services#12]
Hey,
I still don't get the reason for this new TeamSpeak 5 version.

When you connect to the serverquery interface, it shows you "TS3":
```shell
$ ssh serveradmin@localhost -p 10022
serveradmin@localhost's password: 
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.
serveradmin>
serveradmin> version
version=ede8d9a7 build=1669220335 platform=Linux
error id=0 msg=ok
serveradmin>
```

Overall, it looks like a TeamSpeak 3 server. Only splitted into microservices. 🤔 

What exactly will be the different between the TeamSpeak 3 and 5 server? Except of the fact, that the TeamSpeak 5 server is splitted into microservices.

What is / was the reason for migrating from SQLite and MySQL/MariaDB to PostgreSQL? Will there be a migration tool / solution from e.g. MariaDB to PostgreSQL?

A short table with all available Docker containers and a short description of their purpose would be great. For what is which Docker container responsible? Are they optional or required?

**Comment by Gamer92000** [comment]
> Overall, it looks like a TeamSpeak 3 server. Only splitted into microservices

Not really. The TS3 server part is more or less the same, but with fewer features.

> What exactly will be the different between the TeamSpeak 3 and 5 server?

The entire TS5 server support the new chat system.
You can have your homebase for the global chat system on this server.
The chat supports sending images, files, reactions, etc.

Overall you can see what each container is responsible for by looking at the [ARCHITECTURE.md](https://github.com/TeamSpeak-Systems/ts-services/blob/beta-58rc12/ARCHITECTURE.md).
I recommend you have a look at the entire [README](https://github.com/TeamSpeak-Systems/ts-services/blob/beta-58rc12/README.md) of the latest release.

**Comment by Sebi94nbg** [comment]
Ah, yeah. Totally forgot the architecture image. Thanks for the hint. Embarrassing... 😅

But what about my PostgreSQL questions?

**Comment by BerndSchmecka** [comment]
> Will there be a migration tool / solution from e.g. MariaDB to PostgreSQL?

Yes, there is a [MIGRATION.md](https://github.com/TeamSpeak-Systems/ts-services/blob/beta-58rc12/MIGRATION.md) file which explains the process of migrating old TS3 Databases (which can be sqlite, mariadb or postgres) to the newer format 👍

**Comment by qknight** [comment]
I think most important changes have been mentioned but in general, we are working towards REST interfaces and move parts of the core code-base into micro-services. With this comes the new WebQuery, which let's you control the server using REST, see:

https://github.com/TeamSpeak-Systems/ts-services/tree/beta-58rc12#webquery-teamspeak_server-administration

The RAW/SSH interface is compatible to the TS3 scripts for most parts so you will be able to reuse the scripts you already have with the docker based servers.
