### ISSUE TITLE
Wrong Date format in Build Number

### ISSUE THREAD

**Issue by BerndSchmecka** [TeamSpeak-Systems/ts-services#14]
# Describe the bug
Hi,

the newest version (beta58rc18 / v5.0.0-beta14-rc11) has a wrong date format in the build number (`v5.0.0-beta14-rc11 [Build: b'1674816245']` instead of `v5.0.0-beta14-rc11 [Build: 1674816245]`), which causes TS3 and server lists like ts3index to not correctly parse the build date.

Kind regards

# Used versions/hash
ts-services `beta58rc18` / `teamspeak_server v5.0.0-beta14-rc11`

**Comment by qknight** [comment]
Where do you see the build number? In the ts5client or in the teamspeak_server log?

**Comment by BerndSchmecka** [comment]
Both in TS3 Client with `Extended Client Info` Theme and in SSH Query.

**Comment by qknight** [comment]
I've just commited this change:

```
-    build_number=check_output(['git', '-C', repo_path, 'show', '-s', '--format=%ct'], stderr=STDOUT).strip()
+    build_number=check_output(['git', '-C', repo_path, 'show', '-s', '--format=%ct'], stderr=STDOUT).strip().decode()
```

Expect this in the next rc or beta release to be fixed. If not, please reopen.

**Comment by qknight** [comment]
Could have used:

    build_number=check_output(['git', '-C', repo_path, 'show', '-s', '--format=%ct'], stderr=STDOUT, text=True).strip()

Not sure which is the better solution but noting this done in case it comes up again.

**Comment by BerndSchmecka** [comment]
Hi,

Just to confirm, this has indeed been fixed and now works as intended. For example TS3 now correctly parses the build number as `v5.0.0-beta14-rc16 (16.03.2023 15:00:27)` 🥳
