### ISSUE TITLE
Cannot set homebase

### ISSUE THREAD

**Issue by strich3** [TeamSpeak-Systems/ts-services#15]
# Describe the bug
I can't use the TeamSpeak server for the homebase. It says it doesn't support homebase yet

# Used versions/hash
ts-services [beta-58rc18](https://github.com/TeamSpeak-Systems/ts-services/releases/tag/beta-58rc18) / teamspeak_server idk

**Comment by strich3** [comment]
![TeamSpeak_zPz7pddKzy](https://user-images.githubusercontent.com/56207893/217267257-82d1f8e9-57b7-4508-81ad-ee14171ec223.png)

**Comment by qknight** [comment]
Which client version are you using?

**Comment by cah-98** [comment]
I get the same issue using client version 5.0.0-beta72 when setting homebase to my server which is version beta-58rc18. It just pops up with the error in the image above. I can connect to the server fine otherwise. its just setting homebase which does not work. If there are any specific logs you would like i can provide them.

**Comment by strich3** [comment]
> 

I'm using 5.0.0-beta_70

**Comment by strich3** [comment]
I can also set the myTS homebase, but the custom server homebase just won't work

**Comment by qknight** [comment]
I've just tried it once more and here I can set my custom server as homebase successfully.

# client
```
Version: 5.0.0-beta72

Report Issue
Report Content
Build Number:
1671465207
Build Date:
19/12/2022, 16:53:27
Chromium Version:
108.0.0.0
```
# server

seen from ts5client:

`v5.0.0-beta14-rc11 • Linux `

and the release:

`beta-58rc18`

**Comment by qknight** [comment]
Can you provide a setup where this can be reproduced? I know this might be much to ask but would make it much more accessible from my side. I'll check which logs would be interesting.

**Comment by strich3** [comment]
https://youtu.be/wvZPJb6xREU

**Comment by strich3** [comment]
I am using windows 11 btw

**Comment by cah-98** [comment]
I am also using windows 11.

**Comment by strich3** [comment]
> I am also using windows 11.

But on beta_72 it's known that you can't set your homebase

**Comment by Gamer92000** [comment]
> https://youtu.be/wvZPJb6xREU

This does not look like the correct server version on branch `beta-58rc18`. The client should show server version `v5.0.0-beta14-rc11` and not a build number.

**Comment by strich3** [comment]
I just used the latest tag, how i should supposed to be

**Comment by Footsiefat** [comment]
Same issue here

**Comment by qknight** [comment]
@strich3 has this been resolved?
