### ISSUE TITLE
synapse version specified in docker-compose.yaml is way out of date

### ISSUE THREAD

**Issue by ninja85a** [TeamSpeak-Systems/ts-services#16]
# Describe the bug
in docker-compose.yaml you are specifying 1.61 of synapse which is over 6 months out of date, why? just pull from the latest tag

**Comment by qknight** [comment]
First, what new features would you need, which are not there in 1.61?

Other than that, we patch the synapse image during our setup run. These patches need to be adapted and tested which consumes quite some time on our end:

* homeserver.yaml creation
* appserver yaml creation
* teamspeakrules.py patching

Currently we focus our work at other places, especially as there are no urgent requirements to update synapse ATM.
