### ISSUE TITLE
Multiple TeamSpeak instances on one host?

### ISSUE THREAD

**Issue by Sarsum** [TeamSpeak-Systems/ts-services#19]
Is there any recommended way (provided) to host multiple different TeamSpeak server instances (NOT virtual servers). Different dedicated instances with different IPs etc. on a single host?

The port bindings in the `docker-compose.yml` are not limited to a single ip. I therefore would need to do it myself.
Additionally, there seems to be quite a significant amount of unnecessary multiple instances of containers (e.g. Traefik, potentially MinIO) when starting multile stacks.

I'd love to see a solution for this.

**Comment by Sarsum** [comment]
Hello,

thank you for your reply!

We are a customer with a ATHP license. Does that qualify us as a core customer?

I hoped there would be a different solution that overring the port mappings in the docker-compose.yaml to make updates easier. For example by using an environment variable in the docker-compose.yaml for the IP which is set to 0.0.0.0 by default and can be overridden / changed in a .env file.
Currently, updates can be breaking when there are changes in the docker-compose.yaml by your end.

**Comment by qknight** [comment]
If you want to bind to a specific IPv4 address you can do this:

# traefik

```
- "--entrypoints.web.address=1.2.3.4:80"
- "--entrypoints.websecure.address=1.2.3.4:443"
```

# teamspeak

```
teamspeak:
...
    ports:
      - "1.2.3.4:9987:9987/udp"
      - "1.2.3.4:10022:10022/tcp" # SSH, 'secure' Telnet
      - "1.2.3.4:10011:10011/tcp" # RAW, Telnet
```

See also https://github.com/TeamSpeak-Systems/ts-services/blob/beta-58rc20/teamspeak-services-diagram/teamspeak-services-diagram.svg

I'll add this as a section in the README.md on future releases.

If you need IPv4+IPv6 bindings at the same time, I don't have an answer yet.

**Comment by Sarsum** [comment]
Thanks, I'll try that!

I thought of something like this:
```
      ports:
        - "$IP_BIND:-0.0.0.0}:9987:9987"
```
With this you don't need an override file and the overrides by us would not break anything in case you guys add another port binding.
But your solution might also work just fine for the moment.

Just in case anyone else is reading through this issue: naming the file `docker-compose.override.yaml` should automatically apply the overrides when using `docker compose up -d` (you don't need to specify each file with `-f`).

**Comment by qknight** [comment]
@Sarsum what you propose sounds good. I've just updated the comment above about the override.yaml but the docker-compose.override.yaml sounds good, except I guess it must be in the same directory as the docker-compose.yaml and that would be inside the git directory.

We still try to figure out a good way to address complex setups as well as simple ones while figuring out a update workflow.

I like your IPV4_BIND idea, **this could be an option** for the .env file.

`docker compose run --rm setup --domain=example.com --email=admin@example.com --ipv4=1.2.3.4`

**Comment by qknight** [comment]
@Sarsum and also keep in mind, that you want to override the 'name' attribute. If you don't do this, all deployments will have the same container/volume names which is NOT what you want.

**Comment by Sarsum** [comment]
`except I guess it must be in the same directory as the docker-compose.yaml and that would be inside the git directory.`
This shouldn't be an issue as long as you (TeamSpeak) are not creating a `docker-compose.override.yaml` in the main repo. (Which would be kind of weird, as I see no usecase)
I just verified it by checking out beta-58rc19, creating the file, then checking out beta58-rc20.

Thanks for the "name" reminder - I am aware of that!
