### ISSUE TITLE
Undocumented ability to disable TLS in docker compose

### ISSUE THREAD

**Issue by Cj-Herman** [TeamSpeak-Systems/ts-services#21]
The documentation lists that:

> For HTTPS all network traffic is passed to [Traefik](https://traefik.io/traefik/). This service is a reverse HTTP proxy. It first decrypts the HTTPS traffic to HTTP. It will then look at the URL that is requested and then send the request to the proper service unencrypted.

> As mentioned, Traefik handles HTTPS traffic. By default, Traefik is configured to use [Let's Encrypt](https://letsencrypt.org/) to obtain and use an SSL certificate for your domain. This default should ensure that the administrator does not need to do any additional steps to setup encryption besides running our setup utility which is discussed later.

This is said to be documented in the docker compose file, however I don't see any configurations that point to the ability to disable the servers built in Let's Encrypt setup.

I run servers behind an Nginx reverse proxy since I have many services that need these ports, and I forward based on domain name.

Am I missing something or is there no ability to disable this functionality at this time?

# Used versions/hash
ts-services beta58-rc20

**Comment by sruusk** [comment]
Are there any plans to properly support other reverse proxies? 

I managed to get it working somewhat by setting the domain to 127.0.0.1 during setup, but the chat and file browser won't work even though the webquery help page loads.

I get this error in the client console.
![image](https://github.com/TeamSpeak-Systems/ts-services/assets/57395313/6294e39b-b957-49e2-913d-5ed43a70e10c)

**Comment by Gamer92000** [comment]
This is not a problem with the server itself. This repo merely provides an example of how to get this to run.
With the correct setup, you can create a server behind any reverse proxy. Setting the domain to localhost will not work, as this domain will be passed on to any clients to connect to. So you will need to set the public domain of the server.

**Comment by sruusk** [comment]
I figured as much, but when I set the correct domain, the server responds with 404 to all requests. I can see the requests in traefik logs with the correct path and all, but with a 404 response. Any idea why this is?

**Comment by sruusk** [comment]
I figured as much, but after tinkering with it, I realized that my reverse proxy was overwriting the host header and because of that traefik was returning 404 on every request. After disabling the rewrite of the header, it started working.
