### ISSUE TITLE
TeamSpeak 3 client support

### ISSUE THREAD

**Issue by Sporesirius** [TeamSpeak-Systems/ts-services#22]
Hello,
will the TeamSpeak 5 server support the TeamSpeak 3 client, and if so, will the TS5 server drop support for the TS3 client when the TS5 client comes out of beta?

**Comment by LeonMarcel-HD** [comment]
You will only be able to use Voice and Pokes to communicate, as the new chat / file management system is not supported by the TS3 Client

Update your update Client to the Beta to connect to a TS5 Server

https://pbs.twimg.com/media/Fq9wC68X0AAFxEE?format=png&name=large
