### ISSUE TITLE
Service teamspeak restarting - permission error

### ISSUE THREAD

**Issue by trnxtrnx** [TeamSpeak-Systems/ts-services#23]
Hello. 
If I start services (docker compose up -d), the teamspeak service keeps restarting and in the service log, there is an error: /opt/tsserver/entrypoint.sh: line 167: /var/tsserver/query_ip_allowlist.txt: Permission denied

It happens only when I use tags beta-58rc20, beta-58rc19, beta-58rc18.
When I used tags beta-58rc12 or beta-58rc10, I didn´t have any problem with starting services.

What am I doing wrong? Thanks for any advices.

**Comment by adevries17** [comment]
I ran into this issue as well. Had to add chmod permissions to 777 for the text files and parent directory. It may be possible that lower permissions are required, I haven't gotten around to trying other permission levels yet.

**Comment by qknight** [comment]
This will be fixed with the upcoming beta-58rc22 ts-services release. If the problem persists afterwards please reopen.
