### ISSUE TITLE
Chat room not found error in channel chats

### ISSUE THREAD

**Issue by LeonMarcel-HD** [TeamSpeak-Systems/ts-services#4]
Switching channels on a server too quickly sometimes results in being unable to read/connect to the channel chat. [Server beta-58rc8]

![gif](https://user-images.githubusercontent.com/83507548/202870517-a1501858-82b8-4f48-8510-31925d9e5353.gif)

**Comment by qknight** [comment]
Thanks for the report, this is known and once fixed, I'll report back (TSCLIENT-3298).

**Comment by qknight** [comment]
I've another idea with the teamspeak.client_moved call. I'll implement in TS5SERVER-146 and it might not fix this exact issue but should make moves more robust in general as it puts the emphasis on the invite rather than expecting a successful leave (which sometimes might fail and then also the invite fails ATM).

**Comment by qknight** [comment]
Please try this again with the upcoming release after beta-58rc18. I've added a few changes with the teamspeak.client_moved code which creates the invite on the ts5client side for synapse.

**Comment by LeonMarcel-HD** [comment]
I've checked again and it occurred only 1,2 times while switching ~80 times the channel. I think that it is working more reliable now. 

It may be completely fixed as it happened only on the first few channel switches.

(I would reopen the issue if I find a way to reproduce it again)

**Comment by qknight** [comment]
The new feature is not even in yet. I'll post in this issue once it is. Thanks for your tests.

**Comment by LeonMarcel-HD** [comment]
So it was not implemented in Beta-58rc20?

**Comment by qknight** [comment]
Yes, sorry for that. I'll report back once we have a release for this update.
