### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lupettohf** [TeamSpeak-Systems/ts-services#8]
Can you run both the TS3 server and this beta with the same license?

**Comment by MF-1990** [comment]
Hi,
this new server requires a new license which isn't out yet. In the future you will be able to convert your TS3 license to the new one. We give out more information once were closer to the open beta.

**Comment by lupettohf** [comment]
> Hi, this new server requires a new license which isn't out yet. In the future you will be able to convert your TS3 license to the new one. We give out more information once were closer to the open beta.

Last two questions:

- What is the difference (currently, besides the 32 slot limit) between licensed and unlicensed on the TS5 server
- Can we convert NPL?

**Comment by qknight** [comment]
> What is the difference (currently, besides the 32 slot limit) between licensed and unlicensed on the TS5 server

Same restrictions apply as with TS3, however, as discussed in https://github.com/TeamSpeak-Systems/ts-services/issues/8 you won't be able to use the feeder to propagate your channels.
